(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const unavailable = '取得不可';
  const state = {stream:null,context:null,source:null,analyser:null,monitorGain:null,monitorConnected:false,animationId:0,peak:0,peakAt:0,devices:[],logs:[],inputDetected:false,monitorResult:'未確認',toneResult:'未確認',outputAnswer:'未回答',deviceChangeDetected:false,estimatedLatency:null};
  const ui = {status:$('statusBadge'),start:$('startButton'),stop:$('stopButton'),monitorOn:$('monitorOnButton'),monitorOff:$('monitorOffButton'),refresh:$('refreshButton'),tone:$('testToneButton'),volume:$('monitorVolume'),volumeValue:$('monitorVolumeValue'),mute:$('monitorMute'),warning:$('feedbackWarning'),meter:$('meterFill'),peakMarker:$('peakMarker'),level:$('levelValue'),peak:$('peakValue'),rms:$('rmsValue'),db:$('dbValue'),canvas:$('waveform'),log:$('diagnosticLog')};
  const safe = (value, fallback=unavailable) => value === undefined || value === null || value === '' ? fallback : String(value);
  const yesNo = (value) => value === undefined ? unavailable : value ? 'はい' : 'いいえ';
  const ms = (value) => Number.isFinite(value) ? `${(value*1000).toFixed(1)} ms` : unavailable;
  function log(message, level='INFO'){const line=`[${new Date().toLocaleString('ja-JP')}] [${level}] ${message}`;state.logs.push(line);ui.log.textContent=state.logs.join('\n');ui.log.scrollTop=ui.log.scrollHeight;(level==='ERROR'?console.error:console.log)(line)}
  function setStatus(text, type='idle'){ui.status.textContent=text;ui.status.className=`status-badge ${type}`}
  function renderDl(id, entries){$(id).innerHTML=entries.map(([key,value])=>`<div><dt>${key}</dt><dd>${safe(value)}</dd></div>`).join('')}
  function getTrack(){return state.stream?.getAudioTracks?.()[0] || null}
  function supportInfo(){const media=!!navigator.mediaDevices;const htmlSink=typeof HTMLMediaElement!=='undefined'&&'setSinkId' in HTMLMediaElement.prototype;const contextSink=!!state.context&&'setSinkId' in state.context;const select=media&&typeof navigator.mediaDevices.selectAudioOutput==='function';return{media,htmlSink,contextSink,select,canSelect:htmlSink||contextSink||select}}
  function renderSupport(){const s=supportInfo();renderDl('apiSupport', [['MediaDevices API',s.media?'対応':'未対応'],['HTMLMediaElement.setSinkId',s.htmlSink?'対応':'未対応'],['AudioContext.setSinkId',s.contextSink?'対応':'未対応'],['selectAudioOutput',s.select?'対応':'未対応'],['Webアプリからの出力先指定',s.canSelect?'API対応（ブラウザ制約あり）':'未対応']]);$('outputDecision').textContent=s.canSelect?'出力先指定APIがありますが、利用可否はブラウザの権限と実装に依存します。':'この環境では出力先をWebアプリから指定できません。iOSが音声出力先を自動決定しています。'}
  function renderInfo(){const track=getTrack(),settings=track?.getSettings?.()||{};renderDl('trackInfo',[['マイクのデバイス名',track?.label],['deviceId',settings.deviceId],['groupId',settings.groupId],['トラックのlabel',track?.label],['readyState',track?.readyState],['enabled',track?yesNo(track.enabled):unavailable],['muted',track?yesNo(track.muted):unavailable]]);renderDl('settingsInfo',[['sampleRate',settings.sampleRate],['channelCount',settings.channelCount],['sampleSize',settings.sampleSize],['echoCancellation',settings.echoCancellation===undefined?unavailable:yesNo(settings.echoCancellation)],['noiseSuppression',settings.noiseSuppression===undefined?unavailable:yesNo(settings.noiseSuppression)],['autoGainControl',settings.autoGainControl===undefined?unavailable:yesNo(settings.autoGainControl)],['latency',ms(settings.latency)],['volume',settings.volume]]);const c=state.context;renderDl('contextInfo',[['state',c?.state],['sampleRate',c?.sampleRate],['baseLatency',ms(c?.baseLatency)],['outputLatency',ms(c?.outputLatency)],['currentTime',c?`${c.currentTime.toFixed(3)} s`:unavailable]]);const values=[c?.baseLatency,c?.outputLatency,settings.latency].filter(Number.isFinite);const total=values.length?values.reduce((a,b)=>a+b,0):null;state.estimatedLatency=total;renderDl('latencyInfo',[['baseLatency',ms(c?.baseLatency)],['outputLatency',ms(c?.outputLatency)],['入力latency',ms(settings.latency)],['推定合計遅延',ms(total)]]);renderSummary(total)}
  function browserInfo(){const ua=navigator.userAgent;const browser=/CriOS/.test(ua)?'Chrome (iOS)':/FxiOS/.test(ua)?'Firefox (iOS)':/Safari/.test(ua)&&!/Chrome|Chromium/.test(ua)?'Safari':/Chrome/.test(ua)?'Chrome':'その他';const os=/iPhone OS ([\d_]+)/.exec(ua);return{browser,os:os?`iOS ${os[1].replaceAll('_','.')}`:navigator.platform||unavailable}}
  function summaryEntries(total){const inputs=state.devices.filter(d=>d.kind==='audioinput'),outputs=state.devices.filter(d=>d.kind==='audiooutput'),track=getTrack(),info=browserInfo(),s=supportInfo();return[['マイク取得',track?'成功':state.stream===false?'失敗':'未確認'],['マイク名',track?.label],['audioinput数',inputs.length],['audiooutput数',outputs.length],['入力レベル検出',state.inputDetected?'成功':track?'未検出':'未確認'],['モニター出力',state.monitorResult],['テスト音',state.toneResult],['出力先指定API',s.canSelect?'対応':'未対応'],['実際の音声出力先',state.outputAnswer],['devicechange',state.deviceChangeDetected?'検知済み':'未検知'],['推定遅延',ms(total)],['使用ブラウザ',info.browser],['OS情報',info.os],['実行日時',new Date().toLocaleString('ja-JP')]]}
  function renderSummary(total){renderDl('summaryList',summaryEntries(total))}
  async function ensureContext(){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error('このブラウザはWeb Audio APIに対応していません。');if(!state.context){state.context=new AudioContext();log('AudioContext作成');state.context.addEventListener('statechange',()=>{log(`AudioContext状態変更: ${state.context.state}`);renderInfo()})}if(state.context.state==='suspended')await state.context.resume();renderSupport();return state.context}
  async function refreshDevices(reason='手動'){if(!navigator.mediaDevices?.enumerateDevices){renderDevices([]);log('enumerateDevicesは未対応です','ERROR');return}try{state.devices=await navigator.mediaDevices.enumerateDevices();renderDevices(state.devices);log(`デバイス一覧再取得 (${reason}): ${state.devices.length}件`);renderInfo()}catch(error){log(`デバイス一覧取得エラー: ${error.message}`,'ERROR');renderDevices([])}}
  function renderDevices(devices){const groups=[['audioinput','音声入力'],['audiooutput','音声出力'],['other','その他']];$('deviceLists').innerHTML=groups.map(([kind,title])=>{const list=devices.filter(d=>kind==='other'?!['audioinput','audiooutput'].includes(d.kind):d.kind===kind);return `<section class="device-group"><h3>${title}（${list.length}）</h3>${list.length?list.map((d,i)=>`<article class="device-card"><strong>${safe(d.label,`${title} ${i+1}（名称非公開）`)}</strong><p>kind: ${safe(d.kind)}</p><p>deviceId: ${safe(d.deviceId)}</p><p>groupId: ${safe(d.groupId)}</p></article>`).join(''):'<p class="hint">認識されたデバイスはありません（ブラウザが一覧を公開しない場合があります）。</p>'}</section>`}).join('')}
  async function startMic(){if(state.stream)return;setStatus('マイク許可待ち','wait');ui.start.disabled=true;log('マイク開始要求');try{if(!navigator.mediaDevices?.getUserMedia)throw Object.assign(new Error('MediaDevices APIが利用できません。HTTPSで開いてください。'),{name:'TypeError'});state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});log('マイク許可成功');const context=await ensureContext();state.source=context.createMediaStreamSource(state.stream);state.analyser=context.createAnalyser();state.analyser.fftSize=1024;state.analyser.smoothingTimeConstant=.72;state.source.connect(state.analyser);state.monitorGain=context.createGain();updateMonitorGain();state.monitorConnected=false;ui.stop.disabled=false;ui.monitorOn.disabled=false;setStatus('入力中','live');await refreshDevices('マイク許可後');renderInfo();draw();log('マイク入力開始')}catch(error){state.stream=false;setStatus('エラー','error');ui.start.disabled=false;showError(error);renderInfo()}}
  function showError(error){const names={NotAllowedError:'マイクの利用が拒否されました。Safariのマイク許可、iPhoneの「設定」→Safari→マイク、HTTPSでのアクセス、GitHub Pages上での実行を確認してください。',NotFoundError:'利用できるマイクが見つかりません。',NotReadableError:'マイクを読み取れません。他のアプリが使用していないか確認してください。',OverconstrainedError:'指定したマイク条件を満たせません。',AbortError:'マイク取得が中断されました。',SecurityError:'セキュリティ上の理由でマイクを利用できません。',TypeError:'MediaDevices APIを利用できません。HTTPS環境を確認してください。'};const message=names[error.name]||`予期しないエラー: ${error.message||error}`;log(`${error.name||'Error'}: ${message}`,'ERROR');alert(message)}
  function stopMic(){if(!state.stream)return;disconnectMonitor(false);cancelAnimationFrame(state.animationId);state.animationId=0;state.source?.disconnect();state.analyser?.disconnect();state.monitorGain?.disconnect();state.stream.getTracks().forEach(t=>t.stop());state.stream=null;state.source=null;state.analyser=null;state.monitorGain=null;ui.start.disabled=false;ui.stop.disabled=true;ui.monitorOn.disabled=true;ui.monitorOff.disabled=true;ui.warning.hidden=true;setStatus('停止中');clearMeter();log('マイク停止');renderInfo()}
  function draw(){if(!state.analyser)return;const data=new Uint8Array(state.analyser.fftSize);state.analyser.getByteTimeDomainData(data);let sum=0,instantPeak=0;for(const v of data){const n=(v-128)/128;sum+=n*n;instantPeak=Math.max(instantPeak,Math.abs(n))}const rms=Math.sqrt(sum/data.length),level=Math.min(1,rms*3.2),now=performance.now();if(instantPeak>=state.peak){state.peak=instantPeak;state.peakAt=now}else if(now-state.peakAt>700)state.peak=Math.max(instantPeak,state.peak-.008);if(rms>.012&&!state.inputDetected){state.inputDetected=true;$('levelDetection').textContent='検出成功';$('levelDetection').classList.add('live');renderInfo()}ui.meter.style.width=`${level*100}%`;ui.peakMarker.style.left=`${Math.min(99,state.peak*100)}%`;ui.meter.parentElement.setAttribute('aria-valuenow',Math.round(level*100));ui.level.textContent=`${(level*100).toFixed(1)}%`;ui.peak.textContent=`${(state.peak*100).toFixed(1)}%`;ui.rms.textContent=rms.toFixed(4);ui.db.textContent=rms?`${(20*Math.log10(rms)).toFixed(1)} dB`:'−∞ dB';drawWave(data);state.animationId=requestAnimationFrame(draw)}
  function drawWave(data){const canvas=ui.canvas,ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#101827';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#526176';ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();ctx.strokeStyle='#39d6bd';ctx.lineWidth=2;ctx.beginPath();data.forEach((v,i)=>{const x=i/(data.length-1)*w,y=v/255*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
  function clearMeter(){state.peak=0;ui.meter.style.width='0';ui.peakMarker.style.left='0';ui.level.textContent='0.0%';ui.peak.textContent='0.0%';ui.rms.textContent='0.0000';ui.db.textContent='−∞ dB';const ctx=ui.canvas.getContext('2d');ctx.fillStyle='#101827';ctx.fillRect(0,0,ui.canvas.width,ui.canvas.height);ctx.strokeStyle='#526176';ctx.beginPath();ctx.moveTo(0,ui.canvas.height/2);ctx.lineTo(ui.canvas.width,ui.canvas.height/2);ctx.stroke()}
  function updateMonitorGain(){if(state.monitorGain)state.monitorGain.gain.value=ui.mute.checked?0:Number(ui.volume.value)/100;ui.volumeValue.textContent=`${ui.volume.value}%`}
  async function monitorOn(){if(!state.source||state.monitorConnected)return;try{await ensureContext();updateMonitorGain();state.source.connect(state.monitorGain);state.monitorGain.connect(state.context.destination);state.monitorConnected=true;state.monitorResult='成功';ui.monitorOn.disabled=true;ui.monitorOff.disabled=false;ui.warning.hidden=false;setStatus('モニター出力中','live');log('モニター出力ON');renderInfo()}catch(e){state.monitorResult='失敗';showError(e);renderInfo()}}
  function disconnectMonitor(update=true){if(state.monitorConnected){try{state.source?.disconnect(state.monitorGain);state.monitorGain?.disconnect()}catch(_){}state.monitorConnected=false;if(update){ui.monitorOn.disabled=!state.stream;ui.monitorOff.disabled=true;ui.warning.hidden=true;setStatus(state.stream?'入力中':'停止中',state.stream?'live':'idle');log('モニター出力OFF');renderInfo()}}}
  async function playTone(){ui.tone.disabled=true;try{const context=await ensureContext(),osc=context.createOscillator(),gain=context.createGain(),now=context.currentTime;osc.frequency.value=440;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.05,now+.025);gain.gain.setValueAtTime(.05,now+.23);gain.gain.exponentialRampToValueAtTime(.0001,now+.3);osc.connect(gain).connect(context.destination);osc.start(now);osc.stop(now+.31);await new Promise(resolve=>osc.addEventListener('ended',resolve,{once:true}));osc.disconnect();gain.disconnect();log('テスト音再生');renderInfo()}catch(e){state.toneResult='失敗';showError(e);renderInfo()}finally{ui.tone.disabled=false}}
  async function copyText(text,label){try{await navigator.clipboard.writeText(text);log(`${label}をコピー`)}catch(_){const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove();log(`${label}をコピー`)}}
  ui.start.addEventListener('click',startMic);ui.stop.addEventListener('click',stopMic);ui.monitorOn.addEventListener('click',monitorOn);ui.monitorOff.addEventListener('click',()=>disconnectMonitor());ui.refresh.addEventListener('click',()=>refreshDevices('手動'));ui.tone.addEventListener('click',playTone);ui.volume.addEventListener('input',updateMonitorGain);ui.mute.addEventListener('change',updateMonitorGain);$('clearLogButton').addEventListener('click',()=>{state.logs=[];ui.log.textContent=''});$('copyLogButton').addEventListener('click',()=>copyText(state.logs.join('\n'),'ログ'));$('copySummaryButton').addEventListener('click',()=>copyText(summaryEntries(state.estimatedLatency).map(([k,v])=>`${k}: ${safe(v)}`).join('\n'),'診断結果'));$('outputAnswers').addEventListener('click',e=>{const button=e.target.closest('[data-answer]');if(!button)return;document.querySelectorAll('[data-answer]').forEach(b=>b.classList.toggle('selected',b===button));state.outputAnswer=button.dataset.answer;state.toneResult=state.outputAnswer==='音が聞こえない'?'失敗':'成功';$('outputAnswer').textContent=state.outputAnswer;log(`テスト音の出力先回答: ${state.outputAnswer}`);renderInfo()});
  if(navigator.mediaDevices?.addEventListener)navigator.mediaDevices.addEventListener('devicechange',()=>{state.deviceChangeDetected=true;$('deviceChangeNotice').hidden=false;log('devicechange検知');refreshDevices('devicechange')});
  window.addEventListener('pagehide',stopMic);clearMeter();renderSupport();renderDevices([]);renderInfo();refreshDevices('初期表示');log('音声診断ツールを初期化');
})();
